### ISSUE TITLE
Moving to babel 6

### ISSUE THREAD

**Issue by zivl** [lookfirst/gulp-helpers#30]
I remember that there was a trial to move to Babel 6 and then it was reverted. 
What was the reason?
There are a lot of bug fixes + standardization in Babel 6 which can improve this repository and take it on to the next level.

**Comment by lookfirst** [comment]
Jspm doesn't support it yet.

**Comment by lookfirst** [comment]
Sorry to be brief, I was on my phone. I'm happy to see someone add a bable6.js task or something, but I'm not quite sure how to have babel5 and babel6 in the same project. That might be an issue. =(

**Comment by zivl** [comment]
`babel 6` is not playing along with `babel 5`. They have split the modules into few packages and it is dangerous due to conflicts between them.
If the only reason is `jspm` then I think we can move to `webpack` because of the following:
- it has better packaging method
- As from `nodejs` version `5.6.x`, `node`'s package manager is quite as good as of `jspm` or ever better
- gulp-helpers will support `hot-module-replacement` out of the box!

**Comment by lookfirst** [comment]
I'm not moving to webpack any time soon. My entire build is around jspm and I'm not going to switch over to webpack because of babel6 going off the deep end with modularity.
- 'it has better packaging method' is not a real reason, it is subjective without backing proof.
- I'll have to do some research into your npm claim. also subjective without backing proof.
- HMR doesn't work with angular as far as I know. https://github.com/angular/angular.js/issues/11904  yes, some people have come up with hacks using ui-router, but shrug... I'm less than enthusiastic about relying on more hacky code than I already am.

**Comment by zivl** [comment]
I have a winning idea...
There are a lot of projects which uses `webpack` out there - and we don't want to miss them from using the awesome `gulp-helpers`(!)
My suggestion is that I'll add `webpack` task such that the configuration is coming from an outside file anyway. In this way, each project may choose it's packaging system (`webpack/jspm`) and transpiling method (`babel 5/6`) independently. 

everybody wins :)

**Comment by lookfirst** [comment]
Not sure I really understand.

**Comment by zivl** [comment]
to sum up - I'll just add a `webpack` task to live along with all other `gulp-helpers` tasks.

**Comment by lookfirst** [comment]
:+1:

**Comment by zivl** [comment]
ok I'll open a different issue for it since I want to keep track this issue once `jspm` will update to `babel 6`

**Comment by lookfirst** [comment]
All updated!
