### ISSUE TITLE
No way to define your own tasks?

### ISSUE THREAD

**Issue by osiloke** [lookfirst/gulp-helpers#8]
I see that it only looks in the gulp-helpers module tasks folder. How would i define project specific tasks.

**Comment by lookfirst** [comment]
Right, the goal of gulp-helpers is to create re-usable tasks. Project specific tasks are just regular gulp tasks defined in your file. If you have tasks that could be re-usable, then you can submit them as PR's so that everyone can take advantage of them. I'm happy to discuss them first with you too to see if they would be a good fit.

If you don't mind, I'm going to close this issue as it is more of a discussion than an issue. You're welcome to keep the discussion going though.

**Comment by osiloke** [comment]
Well, i needed a jade compiler. I just copied the task for nghtmljs and prepended the gulp-jade task to the pipeline, no biggie. I could add it to my fork. I also may need to make one for riotjs.

**Comment by lookfirst** [comment]
jade and riotjs seem like good additions. feel free to send each in separate PR's. =)
